version: "3.9"
services:
  frontend:
    build:
      context: ./frontend 
    container_name: frontend  
    command: npm start
    restart: always
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/home/app/certs
